### ISSUE TITLE
Please create a Nuxt module

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#1]
It would be SUPER convenient to have a Nuxt module that registers auto-imports and sets everything up to avoid any manual work. That is what Nuxt modules are for and it would be very nice to have a Nuxt module.

Nuxt people are very used to installing modules via Nuxt devtools or via `nuxi module add regle`. Great DX ✨ 

And thanks to Nuxt auto-imports - it means we won't have to manually import rules, composables etc. it would all be automatic.

**Comment by victorgarciaesgi** [comment]
Hey! I agree, I will make a Nuxt module, but I don't think I will make all built-in rules availables as auto-import, it can create conflict with already existing auto-import. But core methods can do the trick yeah
