### ISSUE TITLE
Can we have a shorter way to get "required" fields?

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#10]
In real world forms we often want to add asterisks to required fields like "First Name *" but currently to be able to check if a field is required we have to write a very long check like this:

```ts
r$.$fields.shipmentItems.$each[index].$fields.weight.$rules.required.$active
```

This is kind of long 😅 Do you think we could have some shortcut how to access required state?

Maybe like this 2x shorter way?

```ts
r$.$fields.shipmentItems.$each[index].$isRequired
```

```vue
<template>
    <label>Weight</label>
    <span v-if="r$.$fields.shipmentItems.$each[index].$fields.weight.$rules.required.$active">*</span>
    
    <input v-model="form.shipmentItems[index].weight" />
</template>
```

![image](https://github.com/user-attachments/assets/9bbbdbd5-923b-402c-bd0b-1287f5d50268)

**Comment by victorgarciaesgi** [comment]
Actually that gives me an even better idea to let anyone define their own shortcuts, that would prevent custom stuff in the core as `$active` can work with any rule. I'll try today

**Comment by victorgarciaesgi** [comment]
Also @martinszeltins thanks again for using Regle, reporting bugs and proposing features!! It means a lot 😁😁😁

**Comment by victorgarciaesgi** [comment]
https://regle.vercel.app/core-concepts/extend-properties.html

**Comment by martinszeltins** [comment]
@victorgarciaesgi This might be one of the coolest features in a validation library, I love it! ❤️ 

> thanks again for using Regle, reporting bugs and proposing features!! It means a lot 😁😁😁

I really liked Vuelidate but unfortunately that project was abandoned and not maintained anymore, it had so many bugs. I am really glad that Regle exists and is actively maintained and that reported issues are fixed and implemented 👍🏻
