### ISSUE TITLE
`shortcuts` does not see newly added collection items

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#12]
I have a collection of `shipmentItems`. I draw the asterisk (*) using my own `shortcut`. But when I add a new item to the collection, the `$isRequired` property is `undefined` for the newly created item and so the asterisk does not appear. I have added both - reproduction and video screencast to make it clear.

You can see in my screencast that my first 2 items have asterisk (*) and $isRequired but when I click on "Add Shipment Item" the new item does not have it 😞 

**Reproduction:**
https://stackblitz.com/~/github.com/martinszeltins/regle-test-6

**Screencast:**

https://github.com/user-attachments/assets/25d60e87-c120-4d76-963f-28b2b4cc2414

**Comment by martinszeltins** [comment]
I also noticed that the new item does not validate the rule correctly

![image](https://github.com/user-attachments/assets/cec70632-9b26-4f22-88b5-cbdc68982760)

**Comment by victorgarciaesgi** [comment]
Crap I tested it before! I'll look into this bug

**Comment by victorgarciaesgi** [comment]
Fixed in `0.2.6`

**Comment by martinszeltins** [comment]
> Fixed in `0.2.6`

Works as expected now! Thanks!
