### ISSUE TITLE
`$validate()` does not show error messages

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#13]
It seems like `r$.$validate()` does not work. It doesn't show any validation messages. I have set `autoDirty: false`. I also noticed that there is another method called `r$.$parse()` which does show error messages. It is confusing. It is not clear what exactly the difference between $parse and $validate is.

**Reproduction:**
https://stackblitz.com/~/github.com/martinszeltins/regle-test-7

Here you can see that when I click on `Save` which calls `r$.validate()` nothing happens. I expected the form to be validated and the error messages to show up.

**Screencast:**

https://github.com/user-attachments/assets/8e77a2aa-7cf5-4da0-ae3a-1a9977381ba3

**Comment by victorgarciaesgi** [comment]
That will be fixed in next release!

`$parse` is better to use because it will also return a type safe output of your form. I will see how to better make the difference

**Comment by victorgarciaesgi** [comment]
Fixed on `0.2.8`. Tested on your repro

**Comment by martinszeltins** [comment]
> Fixed on `0.2.8`. Tested on your repro

Perfect 👌🏻 🥳  Thank you!
