### ISSUE TITLE
[docs] Error parsing JavaScript expression: Unexpected token

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#14]
I wanted to fix some spelling / grammar issues in the docs but I am getting this error:

````
[plugin:vite:vue] Error parsing JavaScript expression: Unexpected token (1:2)
/home/martins/Programming/regle/docs/src/introduction/index.md:58:56
61 |  Result:
62 |  
63 |  <QuickUsage/>
````

The only thing I did was clone the repo and ran `pnpm install && pnpm docs:dev`

Screenshot:
![image](https://github.com/user-attachments/assets/21fe20ad-0fcc-4dac-ae16-0473e1eb242e)

![image](https://github.com/user-attachments/assets/be9b6051-4a99-4d59-9e1e-ead660fdd889)

**Comment by victorgarciaesgi** [comment]
You have to build the project before. `pnpm run build`

**Comment by martinszeltins** [comment]
> You have to build the project before. `pnpm run build`

Ah, thanks. It works now!

**Comment by victorgarciaesgi** [comment]
Thanks for helping this the docs! 🫶
