### ISSUE TITLE
Reactivity broken for a rule dependency

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#16]
Reactivity broken for a rule dependency

I have a rule that depends on `someCondition` ref. When `someCondition` changes, the rule should be re-evaluated. However, it is not. However if I change the value of the field then the rule is re-evaluated.

**Steps to reproduce:**
1. Enter weight value: 2
2. Toggle the condition to be OFF
3. The validation error should go away but it does not. == BUG 🐞 ==
4. Enter weight value: 3
5. Now the validation error is gone. (But it should have disappeared when we toggled the condition.)

Reproduction:
https://stackblitz.com/~/github.com/martinszeltins/regle-test-8

```ts
const extraWeightRule = (myArg: string, index: number) => {
    return withMessage(value => {
        return Number(value) > 1
            && someCondition.value === false
    }, t('totally_not_good', { name: myArg + index }))
}

const rules = computed(() => {
    return {
        shipmentItems: {
            $each: (item, index) => ({
                weight: {
                    extraWeightRule: extraWeightRule('weight banana', index)
                }
            })
        }
    }
})
```

**Comment by martinszeltins** [comment]
Also, I think we should have automated tests for such cases.

**Comment by victorgarciaesgi** [comment]
`withAsync` works the same way, as Vue can't collect dependencies on async functions

**Comment by martinszeltins** [comment]
> This is not a problem from regle, but reactivity on your side, as your dependency `someCondition` is inside a function, Vue can't collect the reference.
> 
> Use `withParams` specificaly for this case

@victorgarciaesgi Oh, I see. I think other people will run into the same "issue" and wonder why it is not working. Do you think we could add a separate section to the docs like "Reactivity caveats" or something like that to clearly explain this?

**Comment by victorgarciaesgi** [comment]
I think it's a good idea yeah!

**Comment by martinszeltins** [comment]
👍🏻 closing this and opening a proper issue to track this in https://github.com/victorgarciaesgi/regle/issues/17
