### ISSUE TITLE
`$each: (value, index)`  - implicitly has an 'any' type

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#18]
TypeScript seems to be complaining about the `value` and `index` inside `$each`. Shouldn't they have types inferred by default not `any`?

Screenshot:
![image](https://github.com/user-attachments/assets/0c434e5a-318e-4933-bfb3-93edd995e81a)

**Comment by victorgarciaesgi** [comment]
That's normal, Typescript can't infer types without any reference. Here you juste a have computed returning an object without any indications.

You need to use either `inferRules`, or `RegleComputedRules` type.

https://regle.vercel.app/typescript/typing-rules.html#computed-rules

**Comment by martinszeltins** [comment]
> That's normal, Typescript can't infer types without any reference. Here you juste a have computed returning an object without any indications.
> 
> You need to use either `inferRules`, or `RegleComputedRules` type.
> 
> [regle.vercel.app/typescript/typing-rules.html#computed-rules](https://regle.vercel.app/typescript/typing-rules.html#computed-rules)

Perfect, it works now as expected! Thanks!
