### ISSUE TITLE
`$validate()` does not return `false` when there are validation errors

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#20]
When I first call `$validate()` and I have validation errors, it does not return false but an object. But if I call it again then I get false.

**Reproduction:**
[stackblitz.com/~/github.com/martinszeltins/regle-test-10](https://stackblitz.com/~/github.com/martinszeltins/regle-test-10)

**Screencast:**

https://github.com/user-attachments/assets/44160143-5c0f-4ebc-8ea6-143169f3c42c

**Comment by victorgarciaesgi** [comment]
That's normal. `$validate` was merged with `$parse`. So it will either return 
- `false` if there is validation errors
- A type safe copy of your form if the form is valid (like zod) https://regle.vercel.app/core-concepts/type-safe-output.html

If it's false the second time it's because your have set server errors

What's weird is that it should be valid the first time, looking at this! I think it's linked to collections

**Comment by martinszeltins** [comment]
> That's normal. `$validate` was merged with `$parse`. So it will either return
> 
> * `false` if there is validation errors
> * A type safe copy of your form if the form is valid (like zod) [regle.vercel.app/core-concepts/type-safe-output.html](https://regle.vercel.app/core-concepts/type-safe-output.html)
> 
> If it's false the second time it's because your have set server errors
> 
> What's weird is that it should be valid the first time, looking at this! I think it's linked to collections

I don't understand. There were validation errors before I called `$validate()` the first time so it should have returned `false`, no? Then I didn't change anything and called it 2nd time and then it returned `false`. Something doesn't look right...

**Comment by victorgarciaesgi** [comment]
I will change the `$validate` return type to make it more clear

**Comment by martinszeltins** [comment]
> Yep the first time it should have return `false`, there is a problem with collections i'm fixing. The second time is normal

Yep! Thank you for fixing all these bugs, it's an amazing library! 😀

**Comment by victorgarciaesgi** [comment]
No problem! Thanks for reporting all this bugs, it's hard to have all the possible cases in mind

**Comment by victorgarciaesgi** [comment]
Fixed in `0.2.10`. Changed the return type of `$validate`.

https://regle.vercel.app/core-concepts/type-safe-output.html#r-validate

**Comment by martinszeltins** [comment]
Works like a charm 🤗
