### ISSUE TITLE
Rule minLength is valid when empty collection

### ISSUE THREAD

**Issue by martinhla** [victorgarciaesgi/regle#23]
When using minLength for example:
```
const { r$ } = useRegle(data, {
  levels: {
    minLength: minLength(2)
  },
});
```

and levels are empty collection `{ levels:[] }` then the validation incorrectly passes. 

**Expected behavior**
Validation should fail, as the collection doesn't meet the minimum length of 2.

**Reproduction**
https://stackblitz.com/edit/vitejs-vite-yywmn2?file=src%2FApp.vue

**Comment by victorgarciaesgi** [comment]
I think I know why. The `minLength` check if the value is not empty first to validate, but consider `[]` empty.
So having `required` here will work.
I'll will exclude arrays from the `isEmpty` helper

**Comment by martinhla** [comment]
Yes, I think that was the problem. I already tried using 'required,' and it worked. Thanks for fix!
