### ISSUE TITLE
Rule is valid ... then not valid - with the same value

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#26]
I noticed that I can enter some value and it will trigger my rule and show the validation error message. But then if I validate the form and enter the **same** value again, it now says that it is valid.

**Reproduction**:
https://stackblitz.com/~/github.com/martinszeltins/regle-test-12

**Screencast**:

Here you can see that at first the value "111" was invalid but later the same "111" value is valid.

https://github.com/user-attachments/assets/3a388f61-e9db-41b5-b9c8-eb78de7771ea

**Comment by victorgarciaesgi** [comment]
You have `someCondition.value === false` in your validator.
When you click on `Fill form`, it turns the condition off.

**Comment by victorgarciaesgi** [comment]
Also for complex rules, I advise to use `createRule`. It will automatically register any param as dependency.
It's also easier to read and safer

```ts
const minWeightRule = createRule({
  validator(value: Maybe<number | string>, min: number, condition: boolean) {
    return Number(value) >= min && condition === false;
  },
  message: (_, { $params: [min, condition] }) => `No good: ${min} ${condition}`,
});


minWeight: minWeightRule(someNumber, someCondition)

```

**Comment by martinszeltins** [comment]
@victorgarciaesgi I always had a question why I should use createRule instead of a simple function, I think this is a good point to add to the docs to clear the confusion.

I will test again with `createRule`. Thanks!

**Comment by victorgarciaesgi** [comment]
I will try to explain better! Basically is to have better syntax and type-safety when you create a rule! :D 
You can also add a custom `active` behaviour to your rule
