### ISSUE TITLE
Not all validation messages show up

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#29]
I noticed that I don't see ALL validation messages show up. For example I have 2 rules - `required` and `minLength` but I only see the message of `required` rule.

**Screenshot:**
![image](https://github.com/user-attachments/assets/20020f12-9c9e-4d96-9e8f-6c08590b67b8)

**Reproduction**:
https://stackblitz.com/~/github.com/martinszeltins/regle-test-13

**Comment by victorgarciaesgi** [comment]
Seems like Stackblitz is down so can't see!
But I guess in your custom rules you don't check if the value is empty before running you validator.
It's a norm for validators to run only if the value is set, all inline validators do it.
https://regle.vercel.app/advanced-usage/validations-helpers.html#runtime-and-type-guards

Imagine a optional field that need a minLength, you wouldn't show a message if nothing is in the field

**Comment by victorgarciaesgi** [comment]
Vuelidate have the same behaviour
