### ISSUE TITLE
`validator` triggering too many times

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#32]
I have a collection with rules. I have only 2 collection items but when the `validator` runs, it runs 100x times which doesn't look correct.

**Reproduction:**
[https://github.com/martinszeltins/regle-testing](https://github.com/martinszeltins/regle-testing)

Basically I have this rule:

```ts
const customCityName = createRule({
    validator(value: Maybe<string>, item: any) {
        console.log('item: ', item)
        return value === 'LA'
    },

    message: ({ $params: [item] }) => {
        const itemStringified = JSON.stringify(item)
        return 'City name must be LA' + itemStringified
    }
})

cities: {
    $each: (item) => ({
        cityName: {
            customCityName: customCityName(item)
        },
    })
}
```

And inside `validator` I have a console log. When I start typing into my field, I see 100x console messages.

It is easier for me to show it with a screencast:

https://github.com/user-attachments/assets/58243ea9-de62-462e-ab0f-299d0461ac0b

**Comment by victorgarciaesgi** [comment]
Ouch yeah definetely triggered too many times, weird because this part is unit tested.
I'll look if there is an edge case

**Comment by victorgarciaesgi** [comment]
This is a complicated case, and don't know if it can be fixed.
This is doing triggering too many times because you reference the value itself as a param: `customCityName(item)`. Triggering a loop of computed

This is not called too many times when doing `customCityName(item.value.cityName)`

**Comment by martinszeltins** [comment]
> This is a complicated case, and don't know if it can be fixed. This is doing triggering too many times because you reference the value itself as a param: `customCityName(item)`. Triggering a loop of computed
> 
> This is not called too many times when doing `customCityName(() => item.value.cityName)`

If this cannot be fixed, maybe it is possible to detect it and show a warning in the console if the user references the value itself as a param?

> Warning: Avoid referencing the value itself as a parameter. Instead, consider using a function reference, e.g., customCityName(() => item.value.cityName).

**Comment by victorgarciaesgi** [comment]
It's ok I found the problem! 👍 

Will add another test case for this

**Comment by victorgarciaesgi** [comment]
Thanks for crash testing all this cases 💪 Will keep your big file for testing

**Comment by martinszeltins** [comment]
Thanks, looks like it's working now! 🙏🏻
