### ISSUE TITLE
Field does not become dirty after touching it

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#33]
I noticed that my field did not become dirty after I touched it.

**Reproduction:**
[https://github.com/martinszeltins/regle-testing](https://github.com/martinszeltins/regle-testing)

**Screencast:**

Here you can see that I touched the cityName field but when calling `$extractDirtyFields()` it returned an empty object.

https://github.com/user-attachments/assets/c8ad18d5-4e0a-41a2-bfe7-b6eab4fb03ae

**Comment by victorgarciaesgi** [comment]
I think the issue is with `$extractDirtyFields()` and nested collections, i'll look

**Comment by victorgarciaesgi** [comment]
Yep,  changed `filterNullishValues` option to only filter objects and arrays

**Comment by martinszeltins** [comment]
Thanks! I tested it and I found one minor issue. I changed `address.cities[0].cityName` field and then called `extractDirtyFields` but got this result:

for some reason `cities[1]` is an empty object but I did not touch `cities[1]`, I only touched `cities[0]`

````
{
    "cities": [
        {
            "cityName": ""
        },
        {}
    ]
}
````

**Comment by victorgarciaesgi** [comment]
Yep that's wanted, for arrays it's better to return an empty object than just `null` I think

**Comment by martinszeltins** [comment]
> Yep that's wanted, for arrays it's better to return an empty object than just `null` I think

Yeah, you're right 👍🏻
