### ISSUE TITLE
Get all dirty fields

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#5]
I have a backend that expects me to send it only the dirty fields via API. I wonder if it is possible to somehow retrieve all fields of my form that are dirty?

For example if this is my form:
```ts
const form = ref<Form>({
        name: 'abc', <----- dirty
        email: '',
        skills: [
            {
                skillName: '',
                level: 0
            },
            {
                skillName: 'SuperPower', <----- dirty
                level: 0
            }
        ],
    })
```

I have 2 fields that are dirty here:
1. name
2. skills[1].skillName

It would be nice if `regle` had some function like `getDirtyFields` that would return me only those fields that are dirty like this:
```ts
{
    name: 'abc',
    skills: [
        null,   <--- this is null because skill[0] does not have ANY dirty fields

        {
            skillName: 'SuperPower'
        }
    ]
}
```

**Comment by victorgarciaesgi** [comment]
Yeah that would be totally possible to add!

**Comment by kyong9793** [comment]
+1

**Comment by victorgarciaesgi** [comment]
@martinszeltins @kyong9793 , should it extract only dirty fields that are `valid` ? Should it perform a `validate` before getting the values?

**Comment by victorgarciaesgi** [comment]
It's available in `0.2.3` under `r$.$extractDirtyFields`.
There is one parameter `filterNullishValues` that defaults to `true`. That will only return defined values. 
Use `r$.$extractDirtyFields(false)` if you want don't want any filtering.

I need to add doc for it

**Comment by victorgarciaesgi** [comment]
To note also, this method is available at every nested level of your state.
In your exemple you can do `r$.$fields.skills.$extractDirtyFields()`

**Comment by victorgarciaesgi** [comment]
https://regle.vercel.app/core-concepts/validation-properties.html#extractdirtyfields
