### ISSUE TITLE
External errors not being set correctly

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#6]
There seem to be a few problems with external errors that I have noticed.

1. If a field does not have client-side validation rules set at all then external errors will not be set.
2. When I fill out my form and submit it (validateForm) then external errors are not shown.

Reproduction link:
https://stackblitz.com/~/github.com/martinszeltins/regle-test-3

Screenshot 1
![extern-err-1](https://github.com/user-attachments/assets/a2e2f7eb-825b-4b61-be34-0fcb6427261c)

Screenshot 2
![external-err-2](https://github.com/user-attachments/assets/dc3a659b-562d-429b-a165-94ffde3c95d6)

**Comment by victorgarciaesgi** [comment]
I'm working on this

**Comment by victorgarciaesgi** [comment]
Fixed the behaviour on `0.0.14`, also added type inference for properties in externalErrors that are not in the rules declation. Still need to to it for the `regle.$fields` types. Also need to add tests still
Thanks for the bug reporting!

**Comment by martinszeltins** [comment]
@victorgarciaesgi Thank you! 🙏🏻
