### ISSUE TITLE
How to access the parent object in a collection rule?

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#7]
I have a rule on a collection item but I need to be able to access a property on the parent object but there doesn't seem to be a way to do that.

For example in this form I want to add a rule that the `skillName` must be 'FIRE' but only if `isDeleted` is false. But I can't access the `isDeleted` property from the parent object.

```vue
const form = ref({
    name: '',
    skills: [
        // skillName must be "FIRE" but only if isDeleted is false !!
        { skillName: '', level: 1, isDeleted: false }, 
    ]
})
```

I think Vuelidate had a way to access the sibling state:

```ts
export type ValidatorFn <T = any, K = any, S = any> = (value: T, siblingState: K, vm: S) => boolean | ValidatorResponse | Promise<boolean | ValidatorResponse>;
```

But I can't find siblingState for regle and what if we need to access a property higher up the tree? Perhaps it would be a good idea to be able to get full path to current validation field like `shipment.collection[0].item.items[1].weight`

Reproduction link:
https://stackblitz.com/~/github.com/martinszeltins/regle-test-4

Here is my code (see reproduction for full code):
```ts
const { errors, validateForm, regle } = useRegle(form, () => ({
    name: {
        required,
    },

    skills: {
        $each: {
            skillName: {
                // skillName must be "FIRE" but ONLY if this skill is not deleted !!!
                // We need to access the "isDeleted" property of the current skill (parent)
                myRule: withMessage((value) => value === 'FIRE', 'Skill name must be FIRE'),
            },
        },
    }
}))
```

**Comment by victorgarciaesgi** [comment]
Yep I have no way to do this actually! I'll find a way

**Comment by martinszeltins** [comment]
> Yep I have no way to do this actually! I'll find a way

My suggestion would be to add the full path to the current validation position, for example:

```ts
const { errors, validateForm, regle } = useRegle(form, () => ({
    items: {
        skills: {
            $each: {
                skillName: {
                    myRule: withMessage((value, $path) => {
                        // $path is current position - 'items.skills[0].skillName'
                        return value === 'test' ? true : false
                    }),
                },
            },
        }
    }
}))
```

Maybe there is a better way to do this.

**Comment by victorgarciaesgi** [comment]
Add support for this in the new release `0.0.15`, while keeping type safety.
 
You can write it like this now

```ts
const { errors, validateForm, regle } = useRegle(form, () => ({
    items: {
        skills: {
            $each: (item) => ({
                skillName: {
                    myRule: withMessage((value) => {
                        return item.skillName === 'test' ? true : false
                    }),
                },)
            },
        }
    }
}))
```

I'm still in the process of finalising docs and tests, not funniest part! But progressing

**Comment by martinszeltins** [comment]
@victorgarciaesgi awesome! I am wondering how to access a grand-parent further up the tree, for example if I had this rule:

How to access `parent.isDeleted` in `myRule`?

```ts
const { errors, validateForm, regle } = useRegle(form, () => ({
    parent: {
        items: {
            skills: {
                $each: {
                    skillName: {
                        myRule: withMessage((value) => {
                            return parent.items.skills.length > 1 ? true : false
                        }),
                    },
                },
            },
        },
    },
}))
```

**Comment by martinszeltins** [comment]
> For this you can just use your normal state as you already have access to it. `form.parent.items.skills`

But you can't know the specific item being validated, for example if you have the following form and rule, I don't know the index of `parents` array and I don't know the index of `items` array. That would be the issue if you have multiple $each.

parents[0].items[1].skills[1].skillName

````
const { errors, validateForm, regle } = useRegle(form, () => ({
    parents: {
        items: {
            skills: {
                $each: {
                    skillName: {
                        myRule: withMessage((value) => {
                            return parent.items.skills.length > 1 ? true : false
                        }),
                    },
                },
            },
        },
    },
}))
````

**Comment by victorgarciaesgi** [comment]
In your exemple `parents` and `items` aren't arrays? You didn't declare a `$each` validator. And it works the same way, just chain callbacks

```ts
const { errors, validateForm, regle } = useRegle(form, () => ({
    parents: {
        $each: (parent) => ({
            items: {
                $each: (item) => ({
                    skills: {
                        $each: (skill) => ({
                            skillName: {
                                myRule: withMessage((value) => {
                                    return parent.items.skills.length > 1 ? true : false
                                }),
                            },
                        }),
                    },
                })
            }
        })
    },
}))
```

**Comment by victorgarciaesgi** [comment]
Yep totally, just added it in `0.0.16`
```ts
$each: (skill, index) => ...
```

**Comment by victorgarciaesgi** [comment]
https://regle.vercel.app/advanced-usage/collections.html#accessing-the-current-item-state
