### ISSUE TITLE
`It seems that regle is not a Nuxt module` when adding Nuxt module

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#8]
I was following the docs here to install Regle as a Nuxt module and I got the following message:

```sh
$ nuxi module add regle 

WARN  It seems that regle is not a Nuxt module.                                                                                                                  7:36:18 PM


❯ Do you want to continue installing `regle` anyway?
○ Yes / ● No
```

Perhaps the command in the docs is wrong?

https://regle.vercel.app/introduction/integrations.html#nuxt

I am also not able to find regle on Nuxt modules page:
https://nuxt.com/modules?orderBy=desc&sortBy=createdAt&q=regle

Screenshot:
![image](https://github.com/user-attachments/assets/ea2d43ea-52b0-464f-9b78-dadf30cddba0)

**Comment by victorgarciaesgi** [comment]
Yep that's normal, the PR is still in progress on nuxt-modules part! It will work once it's accepted.

https://github.com/nuxt/modules/pull/1118
