### ISSUE TITLE
How to apply a rule dynamically based on condition?

### ISSUE THREAD

**Issue by martinszeltins** [victorgarciaesgi/regle#9]
I could not find how to add a rule based on some condition. For example, I want to enable the `minLength` rule only if someCondition is true.

```ts
const someCondition = ref(false)

const { r$ } = useRegle(form, {
  name: {
    required,
    minLength: minLength(3) // only if someCondition === true
  }
})
```

**Comment by victorgarciaesgi** [comment]
You can use `applyIf` https://regle.vercel.app/advanced-usage/rules-operators.html#applyif

Or you can do conditionnal assignement on your object. Like `...(condition && {minLength: minLength(6)}`

**Comment by martinszeltins** [comment]
> You can use `applyIf` [regle.vercel.app/advanced-usage/rules-operators.html#applyif](https://regle.vercel.app/advanced-usage/rules-operators.html#applyif)
> 
> Or you can do conditionnal assignement on your object. Like `...(condition && {minLength: minLength(6)}`

Perfect! `applyIf` is what I was looking for. Thanks!
